version: '3.5'

services:

  db:
    image: agftech/db:prod
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    tty: true
    ports: 
      - "3306:3306"
    networks: 
      - nodenet
 
  app:
    image: agftech/app:prod
    container_name: app
    restart: always
    tty: true
    ports: 
      - "3000"
    networks: 
      - nodenet
    depends_on: 
      - db

  nginx:
    image: agftech/nginx:prod
    container_name: nginx
    restart: always
    ports: 
       - "8080:80"
    networks: 
      - nodenet
    depends_on: 
      - app

networks: 
  nodenet:
    driver: bridge